# Docker Compose configuration for Xiaomi Mijia Bluetooth Daemon
# Modern Compose format (no version field required)
# Recommended: Use host network mode for Bluetooth compatibility on Linux

services:
  mijia-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    image: mijia-bluetooth-daemon:latest
    container_name: mijia-daemon
    restart: unless-stopped
    
    # Host network mode for Bluetooth (Linux only)
    # This provides direct access to Bluetooth hardware without device mapping
    network_mode: host
    
    # Run as root for Bluetooth hardware access
    # D-Bus and Bluetooth require root or bluetooth group membership
    user: root
    
    # Note: privileged is NOT needed with host network mode
    # Host network already provides full hardware access
    
    volumes:
      # Configuration file (read-only)
      - ./config/config.yaml:/config/config.yaml:ro
      
      # D-Bus socket for Bluetooth communication (REQUIRED)
      - /var/run/dbus:/var/run/dbus:ro
      
      # Optional: Persistent logs
      - ./logs:/app/logs
    
    # Environment variables - use .env file or override here
    # DO NOT hardcode credentials in this file!
    env_file:
      - .env
    
    environment:
      # Override specific variables if needed
      - MIJIA_LOG_LEVEL=${MIJIA_LOG_LEVEL:-INFO}
      - MIJIA_BLUETOOTH_ADAPTER=${MIJIA_BLUETOOTH_ADAPTER:-0}
    
    # Labels for organization and monitoring
    labels:
      com.docker.compose.project: "xiaomi-ble"
      com.docker.compose.service: "mijia-daemon"
      description: "Xiaomi Mijia BLE thermometer MQTT daemon"
    
    # Health check using pgrep
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'python.*src.main' > /dev/null || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Structured logging configuration
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "com.docker.compose.service"
